
[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.dependencies]
serde = { version = "1.0.228", features = ["derive"] }
toml = "1.0.6"
semver = { version = "1.0.27", features = ["serde"] }
owo-colors = "4.3.0"
veld-error = { path = "./crates/veld-error" }
veld-config = { path = "./crates/veld-config" }
veld-resolver = { path = "./crates/veld-resolver" }
veld-lock = { path = "./crates/veld-lock" }
veld-generator = { path = "./crates/veld-generator" }
veld-fetcher-git = { path = "./crates/veld-fetcher-git" }
reqwest = { version = "0.13.2", features = ["blocking"] }
git2 = "0.20.4"
blake3 = "1.8.3"
chrono = "0.4.44"
petgraph = "0.8.3"
clap = { version = "4.5", features = ["derive"] }
tempfile = "3.27.0"
rstest = "0.26.1"
