[package]
name = "veld-config"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = {workspace = true}
toml = {workspace = true}
semver = { workspace = true }
blake3 = { workspace = true }
veld-error = { version = "0.1.0", path = "../veld-error" }

[dev-dependencies]
rstest = { workspace = true }
tempfile = { workspace = true }
