//! CMake build file generator for veld dependencies.
//!
//! Generates `veld_deps.cmake` files that:
//! - Set `VELD_<NAME>_INCLUDE_DIR` and `VELD_<NAME>_LIB_DIR` variables
//! - Create a `veld_deps` INTERFACE target linking all dependencies
//! - Provide per-dependency import targets (`veld::<name>`)
//!
//! Usage from the project's CMakeLists.txt:
//! ```cmake
//! include(veld_deps.cmake)
//! target_link_libraries(myproject PRIVATE veld_deps)
//! ```

use std::fmt::Write;
use std::path::{Path, PathBuf};

use veld_error::{ErrorCode, ErrorContext, VeldError, VeldResult};

/// A resolved dependency for CMake generation.
#[derive(Debug, Clone)]
pub struct CMakeDependency {
    /// Package name (used for variable/target naming)
    pub name: String,
    /// Path to the source directory
    pub src_path: PathBuf,
    /// Semantic version string (for display/comments)
    pub version: String,
    /// List of packages this dependency requires (names only)
    pub required_by: Vec<String>,
}

/// Configuration for the CMake generator.
#[derive(Debug, Clone)]
pub struct CMakeConfig {
    /// C++ standard to use (e.g., "17", "20")
    pub cxx_standard: String,
    /// Build type ("Debug" or "Release")
    pub build_type: String,
}

impl Default for CMakeConfig {
    fn default() -> Self {
        Self {
            cxx_standard: "17".to_string(),
            build_type: "Debug".to_string(),
        }
    }
}

/// Generate a `veld_deps.cmake` file from a list of resolved dependencies.
///
/// # Arguments
/// * `output_dir` - Directory to write the `veld_deps.cmake` file
/// * `dependencies` - List of resolved dependencies
/// * `config` - CMake configuration options
///
/// # Returns
/// Path to the generated file.
pub fn generate_cmake(
    output_dir: &Path,
    dependencies: &[CMakeDependency],
    config: &CMakeConfig,
) -> VeldResult<PathBuf> {
    let content = render_cmake(dependencies, config)?;
    let output_path = output_dir.join("veld_deps.cmake");

    std::fs::write(&output_path, content).map_err(|e| {
        VeldError::new(
            ErrorCode::FileError(
                output_path.to_string_lossy().into_owned(),
                format!("Failed to write CMake file: {}", e),
            ),
            ErrorContext::new().with_file(output_path.clone()),
        )
    })?;

    Ok(output_path)
}

/// Render the CMake content as a string.
pub fn render_cmake(dependencies: &[CMakeDependency], config: &CMakeConfig) -> VeldResult<String> {
    let mut out = String::new();

    // Header
    writeln!(
        out,
        "# ==========================================================="
    )
    .unwrap();
    writeln!(out, "# Auto-generated by veld — DO NOT EDIT").unwrap();
    writeln!(out, "# Dependencies: {}", dependencies.len()).unwrap();
    writeln!(
        out,
        "# ==========================================================="
    )
    .unwrap();
    writeln!(out).unwrap();

    // Guard
    writeln!(out, "if(DEFINED _VELD_DEPS_INCLUDED)").unwrap();
    writeln!(out, "    return()").unwrap();
    writeln!(out, "endif()").unwrap();
    writeln!(out, "set(_VELD_DEPS_INCLUDED TRUE)").unwrap();
    writeln!(out).unwrap();

    // C++ standard
    writeln!(out, "set(CMAKE_CXX_STANDARD {})", config.cxx_standard).unwrap();
    writeln!(out, "set(CMAKE_CXX_STANDARD_REQUIRED ON)").unwrap();
    writeln!(out).unwrap();

    if dependencies.is_empty() {
        writeln!(out, "# No dependencies").unwrap();
        writeln!(out, "add_library(veld_deps INTERFACE)").unwrap();
        return Ok(out);
    }

    // Per-dependency variables
    writeln!(
        out,
        "# ── Dependency paths ──────────────────────────────────"
    )
    .unwrap();
    for dep in dependencies {
        let var_prefix = dep.name.to_uppercase().replace('-', "_");
        let src_path = dep.src_path.display().to_string();

        writeln!(out, "# {} v{}", dep.name, dep.version).unwrap();
        writeln!(out, "set(VELD_{}_SOURCE_DIR \"{}\")", var_prefix, src_path).unwrap();
        writeln!(
            out,
            "set(VELD_{}_INCLUDE_DIR \"${{VELD_{}_SOURCE_DIR}}/include\")",
            var_prefix, var_prefix
        )
        .unwrap();
        writeln!(
            out,
            "set(VELD_{}_LIB_DIR \"${{VELD_{}_SOURCE_DIR}}/lib\")",
            var_prefix, var_prefix
        )
        .unwrap();
        writeln!(out).unwrap();
    }

    // Check that source directories exist
    writeln!(
        out,
        "# ── Validate dependency sources ──────────────────────"
    )
    .unwrap();
    for dep in dependencies {
        let var_prefix = dep.name.to_uppercase().replace('-', "_");
        writeln!(
            out,
            "if(NOT EXISTS \"${{VELD_{}_SOURCE_DIR}}\")",
            var_prefix
        )
        .unwrap();
        writeln!(
            out,
            "    message(FATAL_ERROR \"veld: dependency '{}' source not found at ${{VELD_{}_SOURCE_DIR}} — run 'veld install' to fetch\")",
            dep.name, var_prefix
        )
        .unwrap();
        writeln!(out, "endif()").unwrap();
        writeln!(out).unwrap();
    }

    // Per-dependency import targets
    writeln!(
        out,
        "# ── Import targets ────────────────────────────────────"
    )
    .unwrap();
    for dep in dependencies {
        let var_prefix = dep.name.to_uppercase().replace('-', "_");

        // Create an INTERFACE library target for each dependency
        writeln!(out, "if(NOT TARGET veld::{})", dep.name).unwrap();
        writeln!(
            out,
            "    add_library(veld::{} INTERFACE IMPORTED)",
            dep.name
        )
        .unwrap();
        writeln!(
            out,
            "    set_target_properties(veld::{} PROPERTIES",
            dep.name
        )
        .unwrap();
        writeln!(
            out,
            "        INTERFACE_INCLUDE_DIRECTORIES \"${{VELD_{}_INCLUDE_DIR}}\"",
            var_prefix
        )
        .unwrap();
        writeln!(out, "    )").unwrap();

        // If there's a lib directory, add link directories
        writeln!(out, "    if(EXISTS \"${{VELD_{}_LIB_DIR}}\")", var_prefix).unwrap();
        writeln!(
            out,
            "        target_link_directories(veld::{} INTERFACE \"${{VELD_{}_LIB_DIR}}\")",
            dep.name, var_prefix
        )
        .unwrap();
        writeln!(out, "    endif()").unwrap();
        writeln!(out, "endif()").unwrap();
        writeln!(out).unwrap();
    }

    // Aggregate target
    writeln!(
        out,
        "# ── Aggregate target ──────────────────────────────────"
    )
    .unwrap();
    writeln!(out, "if(NOT TARGET veld_deps)").unwrap();
    writeln!(out, "    add_library(veld_deps INTERFACE)").unwrap();
    for dep in dependencies {
        writeln!(
            out,
            "    target_link_libraries(veld_deps INTERFACE veld::{})",
            dep.name
        )
        .unwrap();
    }
    writeln!(out, "endif()").unwrap();

    Ok(out)
}

/// Generate a top-level `veld-build.cmake` that provides build integration helpers.
///
/// This file provides:
/// - `veld_add_dependency(<target>)` — links all veld deps to a target
/// - `veld_include_deps(<target>)` — adds include directories for all deps
pub fn generate_build_helper(
    output_dir: &Path,
    dependencies: &[CMakeDependency],
) -> VeldResult<PathBuf> {
    let mut out = String::new();

    writeln!(
        out,
        "# ==========================================================="
    )
    .unwrap();
    writeln!(out, "# veld build helpers — Auto-generated by veld").unwrap();
    writeln!(
        out,
        "# ==========================================================="
    )
    .unwrap();
    writeln!(out).unwrap();
    writeln!(out, "include(${{CMAKE_CURRENT_LIST_DIR}}/veld_deps.cmake)").unwrap();
    writeln!(out).unwrap();

    // Helper function to add deps to a target
    writeln!(out, "function(veld_add_dependencies TARGET)").unwrap();
    writeln!(
        out,
        "    target_link_libraries(${{TARGET}} PRIVATE veld_deps)"
    )
    .unwrap();
    writeln!(out, "endfunction()").unwrap();
    writeln!(out).unwrap();

    // Helper function to include dep headers
    writeln!(out, "function(veld_include_dependencies TARGET)").unwrap();
    for dep in dependencies {
        let var_prefix = dep.name.to_uppercase().replace('-', "_");
        writeln!(
            out,
            "    target_include_directories(${{TARGET}} PRIVATE ${{VELD_{}_INCLUDE_DIR}})",
            var_prefix
        )
        .unwrap();
    }
    writeln!(out, "endfunction()").unwrap();

    let content = out;
    let output_path = output_dir.join("veld-build.cmake");

    std::fs::write(&output_path, content).map_err(|e| {
        VeldError::new(
            ErrorCode::FileError(
                output_path.to_string_lossy().into_owned(),
                format!("Failed to write build helper: {}", e),
            ),
            ErrorContext::new().with_file(output_path.clone()),
        )
    })?;

    Ok(output_path)
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    fn make_test_deps() -> Vec<CMakeDependency> {
        vec![
            CMakeDependency {
                name: "zlib".to_string(),
                src_path: PathBuf::from("/home/user/.local/shared/veld/deps/zl/Zlib/abc123/src"),
                version: "1.3.1".to_string(),
                required_by: vec!["root".to_string()],
            },
            CMakeDependency {
                name: "curl".to_string(),
                src_path: PathBuf::from("/home/user/.local/shared/veld/deps/cu/Curl/def456/src"),
                version: "7.88.0".to_string(),
                required_by: vec!["root".to_string()],
            },
        ]
    }

    #[test]
    fn test_render_cmake_basic() {
        let deps = make_test_deps();
        let config = CMakeConfig::default();
        let content = render_cmake(&deps, &config).unwrap();

        assert!(content.contains("Auto-generated by veld"));
        assert!(content.contains("set(CMAKE_CXX_STANDARD 17)"));
        assert!(content.contains("VELD_ZLIB_SOURCE_DIR"));
        assert!(content.contains("VELD_CURL_SOURCE_DIR"));
        assert!(content.contains("add_library(veld_deps INTERFACE)"));
        assert!(content.contains("veld::zlib"));
        assert!(content.contains("veld::curl"));
    }

    #[test]
    fn test_render_cmake_empty() {
        let deps: Vec<CMakeDependency> = vec![];
        let config = CMakeConfig::default();
        let content = render_cmake(&deps, &config).unwrap();

        assert!(content.contains("No dependencies"));
        assert!(content.contains("add_library(veld_deps INTERFACE)"));
    }

    #[test]
    fn test_render_cmake_custom_config() {
        let deps = make_test_deps();
        let config = CMakeConfig {
            cxx_standard: "20".to_string(),
            build_type: "Release".to_string(),
        };
        let content = render_cmake(&deps, &config).unwrap();

        assert!(content.contains("set(CMAKE_CXX_STANDARD 20)"));
    }

    #[test]
    fn test_generate_cmake_file() {
        let dir = tempdir().unwrap();
        let deps = make_test_deps();
        let config = CMakeConfig::default();

        let path = generate_cmake(dir.path(), &deps, &config).unwrap();
        assert!(path.exists());
        assert!(path.ends_with("veld_deps.cmake"));

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("veld::zlib"));
    }

    #[test]
    fn test_generate_build_helper() {
        let dir = tempdir().unwrap();
        let deps = make_test_deps();

        let path = generate_build_helper(dir.path(), &deps).unwrap();
        assert!(path.exists());

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("veld_add_dependencies"));
        assert!(content.contains("veld_include_dependencies"));
    }
}
