//! CMake build file generator for veld dependencies.
//!
//! Generates `veld_deps.cmake` files that:
//! - Set `VELD_<NAME>_INCLUDE_DIR` and `VELD_<NAME>_LIB_DIR` variables
//! - Create a `veld_deps` INTERFACE target linking all dependencies
//! - Provide per-dependency import targets (`veld::<name>`)
//!
//! Usage from the project's CMakeLists.txt:
//! ```cmake
//! include(veld_deps.cmake)
//! target_link_libraries(myproject PRIVATE veld_deps)
//! ```

use std::fmt::Write;
use std::path::{Path, PathBuf};

use veld_error::{ErrorCode, ErrorContext, VeldError, VeldResult};

/// A resolved dependency for CMake generation.
#[derive(Debug, Clone)]
pub struct CMakeDependency {
    /// Package name (used for variable/target naming)
    pub name: String,
    /// Path to the source directory
    pub src_path: PathBuf,
    /// Semantic version string (for display/comments)
    pub version: String,
    /// List of packages this dependency requires (names only)
    pub required_by: Vec<String>,
}

/// Configuration for the CMake generator.
#[derive(Debug, Clone)]
pub struct CMakeConfig {
    /// C++ standard to use (e.g., "17", "20")
    pub cxx_standard: String,
    /// Build type ("Debug" or "Release")
    pub build_type: String,
    /// Optimization flag (e.g., "-O0", "-O2", "-O3")
    pub optimization_flag: String,
    /// Whether to enable position-independent code
    pub pic: bool,
    /// Whether to enable link-time optimization
    pub lto: bool,
    /// Sanitizer names to enable (e.g., "address", "undefined")
    pub sanitizers: Vec<String>,
}

impl Default for CMakeConfig {
    fn default() -> Self {
        Self {
            cxx_standard: "17".to_string(),
            build_type: "Debug".to_string(),
            optimization_flag: "-O0".to_string(),
            pic: true,
            lto: false,
            sanitizers: vec![],
        }
    }
}

/// Project-level configuration for CMakeLists.txt generation.
#[derive(Debug, Clone)]
pub struct CMakeProjectConfig {
    /// Project name (from manifest.package.name)
    pub project_name: String,
    /// Project version (from manifest.package.version)
    pub project_version: String,
    /// Optional project description
    pub description: Option<String>,
    /// C++ standard (e.g., "17", "20")
    pub cxx_standard: String,
    /// CMake language list (e.g., "C CXX")
    pub languages: String,
}

impl Default for CMakeProjectConfig {
    fn default() -> Self {
        Self {
            project_name: "myproject".to_string(),
            project_version: "0.1.0".to_string(),
            description: None,
            cxx_standard: "17".to_string(),
            languages: "C CXX".to_string(),
        }
    }
}

/// Generate a `veld_deps.cmake` file from a list of resolved dependencies.
///
/// # Arguments
/// * `output_dir` - Directory to write the `veld_deps.cmake` file
/// * `dependencies` - List of resolved dependencies
/// * `config` - CMake configuration options
///
/// # Returns
/// Path to the generated file.
pub fn generate_cmake(
    output_dir: &Path,
    dependencies: &[CMakeDependency],
    config: &CMakeConfig,
) -> VeldResult<PathBuf> {
    let content = render_cmake(dependencies, config)?;
    let output_path = output_dir.join("veld_deps.cmake");

    std::fs::write(&output_path, content).map_err(|e| {
        VeldError::new(
            ErrorCode::FileError(
                output_path.to_string_lossy().into_owned(),
                format!("Failed to write CMake file: {}", e),
            ),
            ErrorContext::new().with_file(output_path.clone()),
        )
    })?;

    Ok(output_path)
}

/// Render the CMake content as a string.
pub fn render_cmake(dependencies: &[CMakeDependency], config: &CMakeConfig) -> VeldResult<String> {
    let mut out = String::new();

    // Header
    writeln!(
        out,
        "# ==========================================================="
    )
    .unwrap();
    writeln!(out, "# Auto-generated by veld — DO NOT EDIT").unwrap();
    writeln!(out, "# Dependencies: {}", dependencies.len()).unwrap();
    writeln!(
        out,
        "# ==========================================================="
    )
    .unwrap();
    writeln!(out).unwrap();

    // Guard
    writeln!(out, "if(DEFINED _VELD_DEPS_INCLUDED)").unwrap();
    writeln!(out, "    return()").unwrap();
    writeln!(out, "endif()").unwrap();
    writeln!(out, "set(_VELD_DEPS_INCLUDED TRUE)").unwrap();
    writeln!(out).unwrap();

    // C++ standard
    writeln!(out, "set(CMAKE_CXX_STANDARD {})", config.cxx_standard).unwrap();
    writeln!(out, "set(CMAKE_CXX_STANDARD_REQUIRED ON)").unwrap();
    writeln!(out).unwrap();

    // Build type
    writeln!(out, "set(CMAKE_BUILD_TYPE \"{}\")", config.build_type).unwrap();
    writeln!(out).unwrap();

    // Compiler flags based on build type
    writeln!(
        out,
        "# ── Build type: {} ──────────────────────────────────",
        config.build_type
    )
    .unwrap();

    let base_flags = format!("{}", config.optimization_flag);

    // Debug-specific flags
    if config.build_type == "Debug" {
        writeln!(
            out,
            "set(CMAKE_C_FLAGS \"${{CMAKE_C_FLAGS}} -g -O0 -DDEBUG\")"
        )
        .unwrap();
        writeln!(
            out,
            "set(CMAKE_CXX_FLAGS \"${{CMAKE_CXX_FLAGS}} -g -O0 -DDEBUG\")"
        )
        .unwrap();
    } else {
        // Release-specific flags
        writeln!(
            out,
            "set(CMAKE_C_FLAGS \"${{CMAKE_C_FLAGS}} {} -DNDEBUG\")",
            base_flags
        )
        .unwrap();
        writeln!(
            out,
            "set(CMAKE_CXX_FLAGS \"${{CMAKE_CXX_FLAGS}} {} -DNDEBUG\")",
            base_flags
        )
        .unwrap();
    }
    writeln!(out).unwrap();

    // PIC (position-independent code)
    if config.pic {
        writeln!(out, "set(CMAKE_POSITION_INDEPENDENT_CODE ON)").unwrap();
        writeln!(out).unwrap();
    }

    // LTO (link-time optimization)
    if config.lto {
        writeln!(out, "set(CMAKE_INTERPROCEDURAL_OPTIMIZATION ON)").unwrap();
        writeln!(out).unwrap();
    }

    // Sanitizers
    if !config.sanitizers.is_empty() {
        writeln!(out, "# ── Sanitizers ─────────────────────────────────────").unwrap();
        let mut sanitizer_flags: Vec<String> = Vec::new();
        for sanitizer in &config.sanitizers {
            match sanitizer.as_str() {
                "address" => sanitizer_flags.push("-fsanitize=address".to_string()),
                "undefined" => sanitizer_flags.push("-fsanitize=undefined".to_string()),
                "thread" => sanitizer_flags.push("-fsanitize=thread".to_string()),
                "memory" => sanitizer_flags.push("-fsanitize=memory".to_string()),
                _ => {}
            }
        }
        if !sanitizer_flags.is_empty() {
            let flags_str = sanitizer_flags.join(" ");
            writeln!(out, "set(VELD_SANITIZER_FLAGS \"{}\")", flags_str).unwrap();
            writeln!(
                out,
                "set(CMAKE_C_FLAGS \"${{CMAKE_C_FLAGS}} ${{VELD_SANITIZER_FLAGS}}\")"
            )
            .unwrap();
            writeln!(
                out,
                "set(CMAKE_CXX_FLAGS \"${{CMAKE_CXX_FLAGS}} ${{VELD_SANITIZER_FLAGS}}\")"
            )
            .unwrap();
            writeln!(out, "set(CMAKE_EXE_LINKER_FLAGS \"${{CMAKE_EXE_LINKER_FLAGS}} ${{VELD_SANITIZER_FLAGS}}\")").unwrap();
        }
        writeln!(out).unwrap();
    }

    if dependencies.is_empty() {
        writeln!(out, "# No dependencies").unwrap();
        writeln!(out, "add_library(veld_deps INTERFACE)").unwrap();
        return Ok(out);
    }

    // Per-dependency variables
    writeln!(
        out,
        "# ── Dependency paths ──────────────────────────────────"
    )
    .unwrap();
    for dep in dependencies {
        let var_prefix = dep.name.to_uppercase().replace('-', "_");
        let src_path = dep.src_path.display().to_string();

        writeln!(out, "# {} v{}", dep.name, dep.version).unwrap();
        writeln!(out, "set(VELD_{}_SOURCE_DIR \"{}\")", var_prefix, src_path).unwrap();
        writeln!(
            out,
            "set(VELD_{}_INCLUDE_DIR \"${{VELD_{}_SOURCE_DIR}}/include\")",
            var_prefix, var_prefix
        )
        .unwrap();
        writeln!(
            out,
            "set(VELD_{}_LIB_DIR \"${{VELD_{}_SOURCE_DIR}}/lib\")",
            var_prefix, var_prefix
        )
        .unwrap();
        writeln!(out).unwrap();
    }

    // Check that source directories exist
    writeln!(
        out,
        "# ── Validate dependency sources ──────────────────────"
    )
    .unwrap();
    for dep in dependencies {
        let var_prefix = dep.name.to_uppercase().replace('-', "_");
        writeln!(
            out,
            "if(NOT EXISTS \"${{VELD_{}_SOURCE_DIR}}\")",
            var_prefix
        )
        .unwrap();
        writeln!(
            out,
            "    message(FATAL_ERROR \"veld: dependency '{}' source not found at ${{VELD_{}_SOURCE_DIR}} — run 'veld install' to fetch\")",
            dep.name, var_prefix
        )
        .unwrap();
        writeln!(out, "endif()").unwrap();
        writeln!(out).unwrap();
    }

    // Per-dependency import targets
    writeln!(
        out,
        "# ── Import targets ────────────────────────────────────"
    )
    .unwrap();
    for dep in dependencies {
        let var_prefix = dep.name.to_uppercase().replace('-', "_");

        // Create an INTERFACE library target for each dependency
        writeln!(out, "if(NOT TARGET veld::{})", dep.name).unwrap();
        writeln!(
            out,
            "    add_library(veld::{} INTERFACE IMPORTED)",
            dep.name
        )
        .unwrap();
        writeln!(
            out,
            "    set_target_properties(veld::{} PROPERTIES",
            dep.name
        )
        .unwrap();
        writeln!(
            out,
            "        INTERFACE_INCLUDE_DIRECTORIES \"${{VELD_{}_INCLUDE_DIR}}\"",
            var_prefix
        )
        .unwrap();
        writeln!(out, "    )").unwrap();

        // If there's a lib directory, add link directories
        writeln!(out, "    if(EXISTS \"${{VELD_{}_LIB_DIR}}\")", var_prefix).unwrap();
        writeln!(
            out,
            "        target_link_directories(veld::{} INTERFACE \"${{VELD_{}_LIB_DIR}}\")",
            dep.name, var_prefix
        )
        .unwrap();
        writeln!(out, "    endif()").unwrap();
        writeln!(out, "endif()").unwrap();
        writeln!(out).unwrap();
    }

    // Aggregate target
    writeln!(
        out,
        "# ── Aggregate target ──────────────────────────────────"
    )
    .unwrap();
    writeln!(out, "if(NOT TARGET veld_deps)").unwrap();
    writeln!(out, "    add_library(veld_deps INTERFACE)").unwrap();
    for dep in dependencies {
        writeln!(
            out,
            "    target_link_libraries(veld_deps INTERFACE veld::{})",
            dep.name
        )
        .unwrap();
    }
    writeln!(out, "endif()").unwrap();

    Ok(out)
}

/// Generate a top-level `veld-build.cmake` that provides build integration helpers.
///
/// This file provides:
/// - `veld_add_dependency(<target>)` — links all veld deps to a target
/// - `veld_include_deps(<target>)` — adds include directories for all deps
pub fn generate_build_helper(
    output_dir: &Path,
    dependencies: &[CMakeDependency],
) -> VeldResult<PathBuf> {
    let mut out = String::new();

    writeln!(
        out,
        "# ==========================================================="
    )
    .unwrap();
    writeln!(out, "# veld build helpers — Auto-generated by veld").unwrap();
    writeln!(
        out,
        "# ==========================================================="
    )
    .unwrap();
    writeln!(out).unwrap();
    writeln!(out, "include(${{CMAKE_CURRENT_LIST_DIR}}/veld_deps.cmake)").unwrap();
    writeln!(out).unwrap();

    // Helper function to add deps to a target
    writeln!(out, "function(veld_add_dependencies TARGET)").unwrap();
    writeln!(
        out,
        "    target_link_libraries(${{TARGET}} PRIVATE veld_deps)"
    )
    .unwrap();
    writeln!(out, "endfunction()").unwrap();
    writeln!(out).unwrap();

    // Helper function to include dep headers
    writeln!(out, "function(veld_include_dependencies TARGET)").unwrap();
    for dep in dependencies {
        let var_prefix = dep.name.to_uppercase().replace('-', "_");
        writeln!(
            out,
            "    target_include_directories(${{TARGET}} PRIVATE ${{VELD_{}_INCLUDE_DIR}})",
            var_prefix
        )
        .unwrap();
    }
    writeln!(out, "endfunction()").unwrap();

    let content = out;
    let output_path = output_dir.join("veld-build.cmake");

    std::fs::write(&output_path, content).map_err(|e| {
        VeldError::new(
            ErrorCode::FileError(
                output_path.to_string_lossy().into_owned(),
                format!("Failed to write build helper: {}", e),
            ),
            ErrorContext::new().with_file(output_path.clone()),
        )
    })?;

    Ok(output_path)
}

/// Render a `CMakeLists.txt` skeleton from project config and dependencies.
pub fn render_cmakelists(
    config: &CMakeProjectConfig,
    dependencies: &[CMakeDependency],
) -> VeldResult<String> {
    let mut out = String::new();

    writeln!(
        out,
        "# ==========================================================="
    )
    .unwrap();
    writeln!(out, "# Auto-generated by veld — DO NOT EDIT").unwrap();
    writeln!(out, "# Edit this file only if you need custom build logic.").unwrap();
    writeln!(
        out,
        "# ==========================================================="
    )
    .unwrap();
    writeln!(out).unwrap();

    writeln!(out, "cmake_minimum_required(VERSION 3.15)").unwrap();
    if let Some(ref desc) = config.description {
        writeln!(out, "project({}", config.project_name).unwrap();
        writeln!(out, "    VERSION {}", config.project_version).unwrap();
        writeln!(out, "    LANGUAGES {}", config.languages).unwrap();
        writeln!(out, "    DESCRIPTION \"{}\"", desc).unwrap();
        writeln!(out, ")").unwrap();
    } else {
        writeln!(out, "project({}", config.project_name).unwrap();
        writeln!(out, "    VERSION {}", config.project_version).unwrap();
        writeln!(out, "    LANGUAGES {}", config.languages).unwrap();
        writeln!(out, ")").unwrap();
    }
    writeln!(out).unwrap();

    writeln!(out, "# Import veld-managed dependencies").unwrap();
    writeln!(
        out,
        "include(${{CMAKE_CURRENT_SOURCE_DIR}}/veld_deps.cmake)"
    )
    .unwrap();
    writeln!(out).unwrap();

    // Build static libraries from dependency sources
    if !dependencies.is_empty() {
        writeln!(
            out,
            "# ── Build dependency libraries ────────────────────────"
        )
        .unwrap();
        for dep in dependencies {
            let var_prefix = dep.name.to_uppercase().replace('-', "_");

            writeln!(
                out,
                "file(GLOB _{}_SOURCES \"${{VELD_{}_SOURCE_DIR}}/src/*.c\" \"${{VELD_{}_SOURCE_DIR}}/src/*.cpp\")",
                var_prefix, var_prefix, var_prefix
            )
            .unwrap();
            writeln!(out, "if(_{}_SOURCES)", var_prefix).unwrap();
            writeln!(
                out,
                "    add_library({} STATIC ${{_{}_SOURCES}})",
                dep.name, var_prefix
            )
            .unwrap();
            writeln!(
                out,
                "    target_include_directories({} PUBLIC ${{VELD_{}_INCLUDE_DIR}})",
                dep.name, var_prefix
            )
            .unwrap();
            writeln!(out, "endif()").unwrap();
            writeln!(out).unwrap();
        }
    }

    writeln!(out, "# Add your sources here").unwrap();
    writeln!(out, "add_executable({}", config.project_name).unwrap();
    writeln!(out, "    # src/main.cpp").unwrap();
    writeln!(out, ")").unwrap();
    writeln!(out).unwrap();

    // Link compiled dependency libraries
    if !dependencies.is_empty() {
        writeln!(out, "# Link dependency libraries").unwrap();
        for dep in dependencies {
            writeln!(
                out,
                "target_link_libraries({} PRIVATE {})",
                config.project_name, dep.name
            )
            .unwrap();
        }
    }

    Ok(out)
}

/// Generate a `CMakeLists.txt` file in the output directory.
///
/// Skips generation if the file already exists (prints a warning to stderr).
///
/// # Returns
/// Path to the (existing or newly created) file.
pub fn generate_cmakelists(
    output_dir: &Path,
    config: &CMakeProjectConfig,
    dependencies: &[CMakeDependency],
) -> VeldResult<PathBuf> {
    let output_path = output_dir.join("CMakeLists.txt");

    if output_path.exists() {
        eprintln!(
            "warning: {} already exists — skipping generation (delete it to regenerate)",
            output_path.display()
        );
        return Ok(output_path);
    }

    let content = render_cmakelists(config, dependencies)?;

    std::fs::write(&output_path, content).map_err(|e| {
        VeldError::new(
            ErrorCode::FileError(
                output_path.to_string_lossy().into_owned(),
                format!("Failed to write CMakeLists.txt: {}", e),
            ),
            ErrorContext::new().with_file(output_path.clone()),
        )
    })?;

    Ok(output_path)
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    fn make_test_deps() -> Vec<CMakeDependency> {
        vec![
            CMakeDependency {
                name: "zlib".to_string(),
                src_path: PathBuf::from("/home/user/.local/shared/veld/deps/zl/Zlib/abc123/src"),
                version: "1.3.1".to_string(),
                required_by: vec!["root".to_string()],
            },
            CMakeDependency {
                name: "curl".to_string(),
                src_path: PathBuf::from("/home/user/.local/shared/veld/deps/cu/Curl/def456/src"),
                version: "7.88.0".to_string(),
                required_by: vec!["root".to_string()],
            },
        ]
    }

    #[test]
    fn test_render_cmake_basic() {
        let deps = make_test_deps();
        let config = CMakeConfig::default();
        let content = render_cmake(&deps, &config).unwrap();

        assert!(content.contains("Auto-generated by veld"));
        assert!(content.contains("set(CMAKE_CXX_STANDARD 17)"));
        assert!(content.contains("VELD_ZLIB_SOURCE_DIR"));
        assert!(content.contains("VELD_CURL_SOURCE_DIR"));
        assert!(content.contains("add_library(veld_deps INTERFACE)"));
        assert!(content.contains("veld::zlib"));
        assert!(content.contains("veld::curl"));
    }

    #[test]
    fn test_render_cmake_empty() {
        let deps: Vec<CMakeDependency> = vec![];
        let config = CMakeConfig::default();
        let content = render_cmake(&deps, &config).unwrap();

        assert!(content.contains("No dependencies"));
        assert!(content.contains("add_library(veld_deps INTERFACE)"));
    }

    #[test]
    fn test_render_cmake_custom_config() {
        let deps = make_test_deps();
        let config = CMakeConfig {
            cxx_standard: "20".to_string(),
            build_type: "Release".to_string(),
            optimization_flag: "-O2".to_string(),
            pic: true,
            lto: true,
            sanitizers: vec![],
        };
        let content = render_cmake(&deps, &config).unwrap();

        assert!(content.contains("set(CMAKE_CXX_STANDARD 20)"));
    }

    #[test]
    fn test_generate_cmake_file() {
        let dir = tempdir().unwrap();
        let deps = make_test_deps();
        let config = CMakeConfig::default();

        let path = generate_cmake(dir.path(), &deps, &config).unwrap();
        assert!(path.exists());
        assert!(path.ends_with("veld_deps.cmake"));

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("veld::zlib"));
    }

    #[test]
    fn test_generate_build_helper() {
        let dir = tempdir().unwrap();
        let deps = make_test_deps();

        let path = generate_build_helper(dir.path(), &deps).unwrap();
        assert!(path.exists());

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("veld_add_dependencies"));
        assert!(content.contains("veld_include_dependencies"));
    }

    fn make_test_project_config() -> CMakeProjectConfig {
        CMakeProjectConfig {
            project_name: "myapp".to_string(),
            project_version: "0.1.0".to_string(),
            description: Some("My test application".to_string()),
            cxx_standard: "17".to_string(),
            languages: "C CXX".to_string(),
        }
    }

    #[test]
    fn test_render_cmakelists_basic() {
        let config = make_test_project_config();
        let deps = make_test_deps();
        let content = render_cmakelists(&config, &deps).unwrap();

        assert!(content.contains("cmake_minimum_required(VERSION 3.15)"));
        assert!(content.contains("project(myapp"));
        assert!(content.contains("VERSION 0.1.0"));
        assert!(content.contains("LANGUAGES C CXX"));
        assert!(content.contains("include(${CMAKE_CURRENT_SOURCE_DIR}/veld_deps.cmake)"));
        assert!(content.contains("add_executable(myapp"));
        assert!(content.contains("add_library(zlib STATIC ${_ZLIB_SOURCES})"));
        assert!(content.contains("add_library(curl STATIC ${_CURL_SOURCES})"));
        assert!(content.contains("target_link_libraries(myapp PRIVATE zlib)"));
        assert!(content.contains("target_link_libraries(myapp PRIVATE curl)"));
    }

    #[test]
    fn test_render_cmakelists_with_description() {
        let config = make_test_project_config();
        let deps: Vec<CMakeDependency> = vec![];
        let content = render_cmakelists(&config, &deps).unwrap();

        assert!(content.contains("DESCRIPTION \"My test application\""));
    }

    #[test]
    fn test_render_cmakelists_without_description() {
        let config = CMakeProjectConfig {
            description: None,
            ..make_test_project_config()
        };
        let deps: Vec<CMakeDependency> = vec![];
        let content = render_cmakelists(&config, &deps).unwrap();

        assert!(!content.contains("DESCRIPTION"));
    }

    #[test]
    fn test_generate_cmakelists_file() {
        let dir = tempdir().unwrap();
        let config = make_test_project_config();
        let deps = make_test_deps();

        let path = generate_cmakelists(dir.path(), &config, &deps).unwrap();
        assert!(path.exists());
        assert!(path.ends_with("CMakeLists.txt"));

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("project(myapp"));
    }

    #[test]
    fn test_generate_cmakelists_no_overwrite() {
        let dir = tempdir().unwrap();
        let cmakelists_path = dir.path().join("CMakeLists.txt");

        // Pre-create a file
        std::fs::write(&cmakelists_path, "custom content").unwrap();

        let config = make_test_project_config();
        let deps = make_test_deps();

        let path = generate_cmakelists(dir.path(), &config, &deps).unwrap();
        assert_eq!(path, cmakelists_path);

        // Should not have been overwritten
        let content = std::fs::read_to_string(&path).unwrap();
        assert_eq!(content, "custom content");
    }
}
